/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/base-footer/base-footer.vue')['default']
    Container: typeof import('./src/components/container/container.vue')['default']
    MusicBox: typeof import('./src/components/music-box/music-box.vue')['default']
    MusicList: typeof import('./src/components/music-list/music-list.vue')['default']
    PlayList: typeof import('./src/components/music-list/play-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanSlider: typeof import('vant/es')['Slider']
  }
}
